discord:
  prefix: "!"
  channel_ids: # List of channel IDs to monitor
    - 1354741091869524100
    - 1332597388153589820
  admin_role_id: 1320711513698472008
  seen_reaction_emoji: "ğŸ‘€"
  approval_reaction_emoji: "ğŸ‘"

openrouter:
  model: "deepseek/deepseek-chat-v3-0324"

vrchat:
  group_id: "grp_55712cfd-77ab-464f-8174-1483616c0c89"

# Other non-sensitive configuration can remain here
